print("version origina:")
###################
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print("\n")
print("\n")
print("\n")
print("flecha doble grande:")
print("        *        "*2)
print("       * *       "*2)
print("      *   *      "*2)
print("     *     *     "*2)
print("    *       *    "*2)
print("   *         *   "*2)
print("  *           *  "*2)
print(" *             * "*2)
print("***           ***"*2)
print("  *           *  "*2)
print("  *           *  "*2)
print("  *************  "*2)
print("\n")
print("\n")
print("\n")
print("Diamante:")
print("      *      ")
print("     * *     ")
print("    *   *    ")
print("   *     *   ")
print("  *       *  ")
print(" *         * ")
print("*           *")
print(" *         * ")
print("  *       *  ")
print("   *     *   ")
print("    *   *    ")
print("     * *     ")
print("      *      ")
print("\n")
print("\n")
print("\n")
print("Corazon:")
print("  **   **  ")
print(" **** **** ")
print(" ********* ")
print("  *******  ")
print("   *****   ")
print("    ***    ")
print("     *     ")



